---
- hosts: 10.0.0.5
  become: yes
  tasks: 
  - name: i want to execute linux command
    command: hostname -f
    register: myfisrsttaskresult

  - name: i want to display myfirsttask result
    debug: 
        msg: "{{myfisrsttaskresult}}"

  - name: i want to install tree
    apt:
      name: tree
      state: present

  - name: i want to install git
    apt: 
      name: git
      state: present
 