---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy file into node side
    copy:
      src: mytestfile
      dest: /home/vinay/myfolder/mytestfile
  
  - name: i want to  install webserver
    apt:
      name: apache2
      state: present

  - name: i want to copy index file into node side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html

  - name: i want to download remote files
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/vinay/myfolder/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes
