---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
   - name: install webserver on ubuntu nodes side
     apt: 
        name: "{{mywebpackonubuntu}}"
        state: present
     when: ansible_os_family=="Debian"
     
   - name: start webserver on ubuntu nodes side
     service: 
        name: "{{mywebpackonubuntu}}"
        state: started
     when: ansible_os_family=="Debian"

   - name: install webserver on redhat nodes side
     dnf:
        name: "{{mywebpackonredhat}}"
        state: present
     when: ansible_os_family=="RedHat"

   - name: start webserver on redhat nodes side
     service: 
        name: "{{mywebpackonredhat}}"
        state: started
     when: ansible_os_family=="RedHat"