---
- hosts: all
  become: yes
  tasks: 
   - name: install webserver on ubuntu nodes side
     apt: 
        name: apache2
        state: present
        
   - name: start webserver on ubuntu nodes side
     service: 
        name: apache2
        state: started

