---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
   - name: install webserver on ubuntu nodes side
     apt: 
        name: apache2
        state: present
     when: ansible_os_family=="Debian"
     
   - name: start webserver on ubuntu nodes side
     service: 
        name: apache2
        state: started

   - name: install webserver on redhat nodes side
     dnf: 
        name: httpd
        state: present
     when: ansible_os_family=="RedHat"

   - name: start webserver on redhat nodes side
     service:
        name: httpd
        state: started
 

